---
- hosts: docker_nodes
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        
    - name: Add docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        state: present
    
    - name: Add docker repository
      apt:
        name:"{{ item  }}"
        state: present
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      update_cache: yes

    - name: Enable and start docker service
      systemd:
        name: docker
        enabled: yes
        state: started